<?php
/** @var MainTemplate $tplData */
if ($tplData->hasErrors()) {
    foreach ($tplData->getErrors() as $error) {
        echo $error . "<br>\n";
    }
}
?>
<form method="post" action="/jelentkezes/check">
    <table border="1">
        <tr>
            <td>Tábor kiválasztása:</td>
            <td><?= MainTemplate::generateSelect('tabor_id', $tplData->getVar('tabor_list'), $tplData->getVar('tabor_id'), array('ID', 'nev')) ?></td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td><input name="email" type="text" value="<?= $tplData->getVar('email') ?>" title=""></td>
        </tr>
        <tr>
            <td>Név előtag (pl.: Dr, ifj, mr, ...)</td>
            <td><input name="nev_elotag" type="text" value="<?= $tplData->getVar('nev_elotag') ?>" title=""></td>
        </tr>
        <tr>
            <td>Vezetéknév</td>
            <td><input name="nev_vezetek" type="text" value="<?= $tplData->getVar('nev_vezetek') ?>" title=""></td>
        </tr>
        <tr>
            <td>Keresztnév (összes :D)</td>
            <td><input name="nev_kereszt" type="text" value="<?= $tplData->getVar('nev_kereszt') ?>" title=""></td>
        </tr>
        <tr>
            <td>Város</td>
            <td><input name="varos" type="text" value="<?= $tplData->getVar('varos') ?>" title=""></td>
        </tr>
        <tr>
            <td>Születésnap</td>
            <td><input name="szuletesnap" type="date" value="<?= $tplData->getVar('szuletesnap') ?>" title=""
                       min="1900.01.01" max="<?= getNOWStr() ?>"></td>
        </tr>
        <tr>
            <td>Közös szállás kulcsszó</td>
            <td><input name="szallas_kulcsszo" type="text" value="<?= $tplData->getVar('szallas_kulcsszo') ?>" title="">
            </td>
        </tr>

        <?php
        if ($tabornapok_list = $tplData->getVar('tabornapok_list')):
            ?>
            <tr>
                <td>Szállás</td>
                <td><?= MainTemplate::generateChecbox('tabornapok_lista', $tabornapok_list, $tplData->getVar('selected_tabornapok_list'), array('ID', 'datum')) ?></td>
            </tr>
            <?php
        endif;
        ?>
        <tr>
            <td>Étkezés</td>
            <td><input name="asd" type="text" title=""></td>
        </tr>
        <tr>
            <td>Ételérzékenység/diéta</td>
            <td><?= MainTemplate::generateChecbox('dieta_erzekenyseg_lista', $tplData->getVar('dieta_list'), $tplData->getVar('selected_dieta_list'), array('ID', 'megnevezes')) ?>
                Egyéb(vesszővel tagolt):<input name="dieta_erzekenyseg_lista[]" type="text" title=""></td>
        </tr>
        <tr>
            <td>Szívesen segítek ezekben</td>
            <td><?= MainTemplate::generateChecbox('segito_munka_lista', $tplData->getVar('segitomunka_list'), $tplData->getVar('selected_segitomunka_list'), array('ID', 'megnevezes')) ?>
                Egyéb(vesszővel tagolt):<input name="segito_munka_lista[]" type="text" title=""></td>
        </tr>
        <tr>
            <td colspan="2">
                <?= $tplData->getVar('aszf') ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input name="send" type="submit" title="Jelentkezés" VALUE="Jelentkezés">
            </td>
        </tr>
    </table>
</form>