<?php
/**
 * Created by PhpStorm.
 * User: White Mage
 * Date: 2022.04.24.
 * Time: 13:24
 */

namespace App\Http\Resources\Json\Tabor\Admin;

use Illuminate\Http\Resources\Json\JsonResource;

class CsoportResource extends JsonResource
{
    public function toArray($request)
    {
        return [1,2,3];
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}